server:
  port: 8080
spring:
  application:
    name: judo-manager-payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/judomanager
    username: root
    password: root
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
tosspayments:
  secret_key: