pipeline {
    agent any

    stages {
        stage('CLONE') {
            steps {
                script{
                    git branch: 'develop', url: 'https://github.com/Ghosttrio/judo-manager.git'
                }
            }
        }
        stage('BUILD'){
            steps{
                dir('judo-manager-eurekaserver') {
                    sh '''
                        ls -al
                        chmod +x gradlew
                        ./gradlew clean build
                    '''
                }
            }
        }
    }
}