spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/judo-manager-dev
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: false # false일 때 sql init 실행 후 ddl auto 실행
  data:
    redis:
      host: localhost
      port: 6379
      password: ghosttrio123
#  sql:
#    init:
#      mode: always
# tosspayment
toss:
  key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6


jwt:
  secret: 5b6a570c9a4425a059451418e186cfb7033ffee07c18b2f4f6762452d4abb54d1dc6fb691f4ef5d602bc4c72ca6b53a749eb1b8a780968da39021310f123d564


kakao:
  client_id: e61b4777d43816865bfbebc87c30aa9b
  client_secret: x0XT6o350cZAqvzWZmVGlj2I1iIZQBS4
  redirect_uri: http://localhost:3000/kakao-login
  grant_type: authorization_code
