server:
  port: 0
spring:
  application:
    name: judo-manager-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/judo-manager-dev
    username: root
    password: root
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.7:8761/eureka